### ISSUE TITLE
Question about "Expansible" naming conflict

### ISSUE THREAD

**Issue by gildegoma** [rastaman/expansible#1]
Hi @rastaman!

I've recently started a project that I also named ["expansible"](https://github.com/gildegoma/expansible). I actually did some github/google search about this name a few weeks ago and was happy to use this name. But I unfortunately forgot to check it again today before I finally created my github repository. Just a few minutes ago, I noticed that you also created this repository five days ago :open_mouth:.

As you were the first in the "github market place" (but only with an empty README file, at least for the visible parts ;-), I would like to check with you if this name is important for your project, and how we can find **two different** names that are pleasant to you and me.

For the context of my project (a Boxen-like tool written in Ansible), `expansible` was quite appealing (see https://github.com/gildegoma/expansible#about-the-name). How important is the name for you? If you really want to use it, no problem, just tell me (as said, you were first!) and I'll rename my project as soon as possible. 

Thanks in advance for your understanding in my "strange" request and your quick reply.

PS: I also have some ideas for Light UI for Ansible, and would love to know more about your project :smiley:

**Comment by rastaman** [comment]
Hi Gilles,

Sorry but I must continue to use this name for my project, because it's 
too late for me to change it, i have buy a wildcard ssl certificate and 
the domain name expansible.io for it. I would have hear from you before 
i buy the domain and certificate i could have renamed it but now it is 
not possible anymore i think. My project is about a light ui to help 
manage hosts and deployments with ansible. Your project sounds like a 
nice idea too!

Best wishes for 2015!
Regards,
Ludo

**Comment by gildegoma** [comment]
@rastaman Thanks for your quick reply. I am quite happy to learn that your **expansible** is not a toy project, and I am looking forward to discover more about it (and possibly contribute too, as I also started to work on similar topic/needs :-).

I'll rename my project. See https://github.com/gildegoma/expansible/issues/5, in case you have any good suggestion ;-)
